apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budget-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "budget-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "budget-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "budget-chart.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port | default "80" }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ include "budget-chart.fullname" . }}-data-0.{{ include "budget-chart.fullname" . }}-headless-service
            - name: DB_PORT
              value: {{ .Values.statefulset.containerPort | default 3306 | quote}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
