apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budget-chart.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "budget-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.statefulset.secrets | nindent 2 }}
