apiVersion: v1
kind: Secret
metadata:
    name: github-auth
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hVzzfwhK2+ZcmIM4FMH7a7XolBvpLyKugJDFO3Jpd9Ojzz0h4XFU3klUjViBfq5qQWT0d7E9os9WZK31E66r+9oFXe+lAxfeq2PYR/qea8ZfrJP1v4x9FN88cC5w5LhF4NhJt1/Cj/hjU45iJR3+BgVA/paJZyDQmLIc8NY+KQqVexSyd+MN7xXeuzlIU2ckZdv1aU72iW+TFYRR3YX9mh01vM6RPKTBraDb588DI38Qbw19dgrUEp3zmDecdfnjJwR86AbU9eo2eAU900PWQxOLxwN5ouFm9Ev4AbZxrHhhIemAOVjM5pdlgS1A0HWlH14WSQks86V3uWgiEpjKXNVH2R7P/iP+v9atHJYsdvxtrh+q8sttKD//HP1ZLeODiNFQ0DTCPoclswxEuq54oyK25ypyZurpWcviD7oUaIaO+3sGp9tnINb1NpTAKPvDyaLuhwYDlAqU1TFcQ8aUwu3yxFqJNx+malmJ4VCF1R6kOFmI/Xylwpf2uFpyogAV7FVlzu1dhCRAY9Lh2exJLXrUGc2ZozM5rALw,iv:BpY1W74Me3lGztHGvoLjcWUUyG8RuNfmQgHYLfg3rGE=,tag:VPBQsH2YR0T6bMwcMa6Y+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:tFtbJgM06rsx+rqGAczyg7xSNcXaIMEBgMyncXfKCoZgr9CrAC0KUkBHMIMScpmPi3WjIG2Ju6Bf+6rXsYYxqMgyn2vEJVIPoya+ZglGEfMJzJBJMVLl+NVDU8I=,iv:FlHSsnjYfOXI7owvzrjaCXofQAnrAs6kG94r6G9Ds74=,tag:cdt7GtuQWai+/F5vS885ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQmNqeUhodW9scU1oZ002
            SENDQXBVZzYyZzB4UHUveXFmMkhTZWJjWFcwCmxIb1R6VFZYQUM4aDdtbjFkR2h4
            bHJxZXRBTEhwcU51ZWtVclRMd3ovNkEKLS0tIG1BdTBqa2tuY2JmUkpTUUNXeGxn
            K3JIb2lBdmpmYk5wZDU4WEh6VDR2M2MKQrWYSi4hA3pmhNIqSQ0K3MsCt0nKTca1
            hF/uVjMrhOYt2CHAx/f8VVmswlILx29WqAwk8amNn2ABichVW9rqPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd2pax67da9fumz38avgzdqhxug02lw00h2y4zlkrrjjdnyr3e3srhxkd8
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-17T10:43:38Z"
    mac: ENC[AES256_GCM,data:4zJ8VzPdwiMM8NUun7/cLwdIy/4CtgHNtlJxqxc9NqnqVngW68xOBJDbn46fToJxpZuJOrFrG6zJ4uYuw1bdAqDM97T6sBAJzKo/cx06EQ4W6p7uns6R1Qujxq6XJnWks8VTpBuTEe6Fcye4of2vFGlr/6P3YdbHEq1G7akEYKE=,iv:JcJk0U65LFK0Wp0eoHTHrmhoQ+B03Q3resYgrZuG4+o=,tag:UjeCOvM3D+VOuV/rZXxvVA==,type:str]
    version: 3.13.2
