---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: budget
  namespace: flux-system
spec:
  image: krupanshi20/budget
  secretRef:
    name: secret-budget-docker
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: budget-policy
  namespace: flux-system
spec:
  filterTags:
    pattern: "^main-[a-fA-F0-9]+-(?P<ts>.*)"
    extract: "$ts"
  imageRepositoryRef:
    name: budget
  policy:
    numerical:
      order: asc
  digestReflectionPolicy: IfNotPresent
