apiVersion: v1
kind: Secret
metadata:
  name: secret-budget-docker
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:NebQre+d+3h/KpRns+IDlEvVezHkrl7fJfbYK61VBJFCEvmtxwMHq6RBtg9wlcVWBqnez7hvLTVKYSNIocn52hnYxVPrXCwdWXdlUF4Xt5oV9B7iHuzVEy9EHxzQ2KeEZCQMYqQSSCAGlnSLO6nJ1+dpXnO+hhqlP8aZe9R3/ZIeCV3KA7RnPqjjAeMDhpqJ7mNsSlr1EAX9GMGR7Htb2WdSpdVEOYR8bO39iJ7Wf3guSbAZBM7+326GFbHNxPNB23JEDLxIWa+APeskR9hko4b7nBWDMqblUML3KAk4/d4owBZnEZp4qA==,iv:Wu3U6t9MkbWX+qYpEM1Or4sP8xwtyO0hiXtbVBFmhCE=,tag:XktPw8auktVlSEAvQ71YWQ==,type:str]
sops:
  age:
    - recipient: age1mnqn4cexq7739pldt4mvq3cd6mu4h956cxha4f47r5v5aetd03nqlgp9rl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWVBNHo3M0hZclcvOWtE
        dFpDWUFMUjQzZFZBLys1bERiY01DYUgwRzNFCnMzMjkxcE5UbjI2WmFLeHdlc2R3
        WEVLbDRRM3k2M0RuZFlPdVlsamZpbmsKLS0tIHQ1OTVmSUNEekM5d3pXaVNnOCtS
        S1ZSczE2TkJvTmEyM2l6czgwMWhjYjAKsCMFI1Qeen14Fl/DS/FmReQCY9QhqTgr
        ZCmypyw+AfGDhSPI5XP7FbZWQnG7ryHMSxw7S+3gYun0PbD9RGvz7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T05:02:50Z"
  mac: ENC[AES256_GCM,data:qv7r4JS6QODHwvw28hVvJGQ2rPOEodRW9yJn9fyn2rKuphsbFMV7mk/2d0cbyOIGQk4FZ6synEs4TgG1FuuD4AdRoJhO6vRHmhTdXlkSonsrW5mRkNhYbdZygMsQuqq97iYT8LmCLGFgqGCJY9zNpWf+aFaiOtqbhlIYGvqeKIM=,iv:c0FN66i/wUV1UO4RWKHh39HrbP3K3X4sWM4OTgyjAgc=,tag:F6Z72EK4Dsq1i2cLWDU7TQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
