apiVersion: v1
kind: Service
metadata:
  name: budget-app-svc
  namespace: budget
spec:
  selector:
    app: budget
  ports:
    - port: 80
      name: app-svc-port
      targetPort: app-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
  namespace: budget
  labels:
    app: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
        - name: budget-app
          image: krupanshi20/budget:main-8a9e24e-1750242271 # {"$imagepolicy": "flux-system:budget-policy"}
          ports:
            - containerPort: 80
              name: app-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-env
                  key: DB_PORT
