apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    namespace: budget
spec:
    selector:
        app: budget
    type: ClusterIP
    clusterIP: None
    ports:
        - port: 3306
          targetPort: mysql-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: budget
    name: mysql
    labels:
        app: budget
spec:
    serviceName: "mysql-svc"
    replicas: 1
    selector:
        matchLabels:
            app: budget
    template:
        metadata:
            labels:
                app: budget
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0
                  ports:
                      - containerPort: 3306
                        name: mysql-port
                  env:
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: database-env
                                key: DB_DATABASE
                      - name: MYSQL_USER
                        valueFrom:
                            configMapKeyRef:
                                name: database-env
                                key: DB_USERNAME
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: database-secret
                                key: DB_PASSWORD
                      - name: MYSQL_RANDOM_ROOT_PASSWORD
                        value: "1"
                  volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
    volumeClaimTemplates:
        - metadata:
              name: mysql-data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 10Gi
