apiVersion: v1
kind: Secret
metadata:
  name: secret-budget-docker
  namespace: budget
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:JPT/VnEXvuddrSfWvtgSuN+jC00MaeNi5kw8oZJfOPiULWqP4xZGrYIl/BT1N4/1GiKvQUh91zHX9UVE/jzLd4KBmA90zdUlmLzg2+4oN0XKtNMnzc7ItcUraYWGw3dHdul3s3tpNlPMMit+Jq7YIIyUbO7UEY7pQBJfDey+faYZJ8q/1mziVkEsoESPn2IK5iZ+N0g+12KP1f77eprwWW6eikO8nWSoNV8TnUqeBoRRh/2X8Q+gBhqJAPFU5brY7s/KWzciDiMsF/rpxABl8lYqq6QGg3M+ejogr7KETIjr53KY4N4C2g==,iv:/OtcpHmzS0s9Sya8oi/ultrD4+LcZaeNoEvDCIvGZ+s=,tag:dyj0qmNId2/icYLH5emojw==,type:str]
sops:
  age:
    - recipient: age1mnqn4cexq7739pldt4mvq3cd6mu4h956cxha4f47r5v5aetd03nqlgp9rl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0ZGWm8ra1JLMDA4akpW
        N1Q0eFBhY0g4ZllURndvTHRqWGZmZTJGczNFCitBdUEzVVRLUVpmbVFHdG0veHBW
        NGZTVHJkVHpicEQ1Y1lBU2RGRlE2NFEKLS0tIFZGbEFFZFF1NEIzYVRWOVBPUndp
        bjUwcDhyaDBRenZrQm5mbDV3cGcyZTgKN0GGneHStB7OJ3RmLXNZ8ymdE049eamh
        34RlBNxJtvCZErRVeTS0ovd6M3/kKP7S5/VXFpLcTPh/aNSdlXMCUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T09:16:42Z"
  mac: ENC[AES256_GCM,data:LzsThTGGbBbnn6gSrORAwA5uJQ+7+JsKYmNA1GWVFEsPZVP0cwxlqNtMFRhzVF+EjeSd1INjx6fGpjQkOVZ+R80umLkszZY4raHKHZOANn7gcCxl9w1KY22PR8310sSLCUr8ZNHyb/+yrXLfnUgO7r9ULevuLrsVZ1s6GCDxNQU=,iv:6qWR+7lgtjc1sZO4VukJj0b1qqsniFbDRD0Z3ls0JeE=,tag:STI3ey8r81+ljtx0rE90ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
