apiVersion: v1
kind: Secret
metadata:
    name: secret-budget-docker
    namespace: budget
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RE23Dsv3Id7ENfb7wxHuhJM9IN4GzG89+2FT4hNVIBPyoK3nLHZXvBZhb85mXydDXC237UFRgFuGRfZRpA9BaEupO+LeDrpPiZkcLn+cFJLxxF29YrDnHzOKUccJ1wWK+lHQCWPn3SuGJd71KxsM3psozI5Ki+5BRsFiabDdXsK4sFNyiFE6HnVg7egTha1sHi6L7vHLkuGn+IXUhsxQLymnbdWppOFUhpof00vG3QYZfKIy3X14hxIEzRhXASUU1iKfKaTpxybPwdjCVUplvnME/DpkPlgPIaQciVQH5VOcUmIw0d3tuw==,iv:xzCTbekUgDCl4W6LereMUuwbOZIgnRHC0Y6dKnq93Uk=,tag:M19DTctvSH8ICabrO1jL0A==,type:str]
sops:
    age:
        - recipient: age1mnqn4cexq7739pldt4mvq3cd6mu4h956cxha4f47r5v5aetd03nqlgp9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQlU3WjRMeVNyWHBMeXRN
            M0VpVE1QV05Wd2wycmtQL21JWXNIbndQRno4Ckt1M1pEVU14Sm85RGZJL0l4NGZH
            UDl0ZkNUbmZLVGhnN0tXN0dqNTI5aFkKLS0tIGlZbS9qOGNxK3BKWnZ0RlFqcXlu
            R3QwZ2l4N0RGVlh2UWljR0k5OEkzRm8KyorlOJYqgBbZtTIpb3xmNCQG3b+stSmH
            KjUKG+3CvuODnVZwAHAYGplJG6ZeGZeqDNadYNXsdyivQjxkdIsJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T05:40:15Z"
    mac: ENC[AES256_GCM,data:4PWW3Wq8coZUqAiDKPT+W81hwp+/e8rHl/qurV/YJxHmudB05Ns4Ld3NJAlAd4dyHMXyLOftO9mW9XKXGpk+xZwiL6Y4UhXNnzW1RgDidhp41Dsr2i/vOEepe6pLTl55KGXlh9SmWbSmjPGhHsuTOVSiDmI0I2xnZs+SlIKzP4o=,iv:ipG4Af30LMA8VK4LpJ7EFI57d/zAMJNWm+SvgnnfMf4=,tag:u0N0XTOd68YNlCi7LwcOQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
