apiVersion: v1
kind: Secret
metadata:
    name: database-secret
    namespace: budget
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ZDC24g==,iv:PbKQ0j0VfgNUjVvifJVdscJW+5ci1n1GswNYSJmwB7w=,tag:z6+OraPGMmqezA2mYwWtiw==,type:str]
sops:
    age:
        - recipient: age1mnqn4cexq7739pldt4mvq3cd6mu4h956cxha4f47r5v5aetd03nqlgp9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOWJTenZtNjkyanBaM2ZU
            eVU1dDZabDZWZTVWVVVmMG5mc2ZIYitQTzJVClZ3OEV1RmlmQlA2dDFYTE9LelIy
            cmc5N3FxZnBTNktIMk8zeTZmMUNocmcKLS0tIGsyclR0Tm5SRlVqM3RBcmhRSUZE
            bFcxUGtQdytyc0sxc2Z1ZHpsMnB0VzgK4nxwtKIgPGQ3Wz+DRyps0uCVHVJrlRRQ
            oH7tjMuY+YlpaHpteun+QefY6saUQ+lcdo8gS+aOzCEml9ZVh+03tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-23T07:04:06Z"
    mac: ENC[AES256_GCM,data:NV63f4oreskztmWqi8TIJsTlxPdKCNKSEd/gV6MUg77/HV7V/4ON3MO4Z12Y0mL71QuetKdDcoLmsEZxe5qRpkdDhkUv77LThHDAa6cq6lYPT97tlCDa6g+8CPEVzuv5gcBcRNcX+k5sKkKp+sA9OibU5fHxE6kUGXLhcRyeF1U=,iv:66x7EPP9mmKkPOf5xwWO9cdgNo+e3gJDwXpXfE/0zdg=,tag:hq1GOqoj26aUU31CkBU1gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
