apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: budget-alert
  namespace: monitoring
  labels:
    release: monitoring-prometheus-helm-release
spec:
  groups:
    - name: BudgetAppAlerts
      rules:
        - alert: ImageChanged
          expr: |
            count(
            kube_pod_container_info{namespace='budget'} unless
            kube_pod_container_info{namespace='budget'} offset 2m
            ) by (namespace, pod, container, image) > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Container image changed"
            description: "The image of container in pod {{ $labels.pod }} has changed to {{ $labels.image }}"
