apiVersion: v1
kind: Secret
metadata:
  name: flux-system-ssh
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCXTNxSdKQ2tBZPDWsEKf8EUs9/WuFW1nODFR1IjiI8dQAAAIgnYN9DJ2Df
    QwAAAAtzc2gtZWQyNTUxOQAAACCXTNxSdKQ2tBZPDWsEKf8EUs9/WuFW1nODFR1IjiI8dQ
    AAAEBwY8lLdFCXVVtf9ieQ+yXdI+ffBTUP4ii8gykRxQOJ1pdM3FJ0pDa0Fk8NawQp/wRS
    z39a4VbWc4MVHUiOIjx1AAAABGZsdXgB
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJdM3FJ0pDa0Fk8NawQp/wRSz39a4VbWc4MVHUiOIjx1
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
