apiVersion: v1
kind: Secret
metadata:
  name: flux-system-ssh
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDA7ppRjXzi3RrZ41QCn
    nQ/9lHBuoJR4lZTs1Kauf7Iec4/+K6JwmsLGcLEGFANB5g+hZANiAARHsir9ex44
    pyK2W/GhX6y41KXfQQ2boTUmf61HMWLyGKrtqTOnDJ2DOc/0tVmeemmAcKmJ3VLo
    ZIiOTOT9A5JiuDv/3CYWteQQwb6O9l372hS1cpdnsTP8I0/Ss2zTsO0=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBEeyKv17HjinIrZb8aFfrLjUpd9BDZuhNSZ/rUcxYvIYqu2pM6cMnYM5z/S1WZ56aYBwqYndUuhkiI5M5P0DkmK4O//cJha15BDBvo72XfvaFLVyl2exM/wjT9KzbNOw7Q==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
