apiVersion: v1
kind: Secret
metadata:
    name: flux-system-ssh
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c31uM8XPEwg8RbWvSxMvfDP96dWfGzL8TSjGHnCWnHltzqlYNYWax+afdL65w9vZnZD9Hdx5BXFQc+DieC9rH7bNVGqb5TX1yrZcyKjfglhsGGApsUMtymaemLso6DY3IZoRPevjcj3XHG6VugcuFGLDITftHeGK9ySt8Me6Zs4UwB/SQ2VuxUK4G3FUyJ5y/Vvw/JD0+sNn60goMN0UNQZGUXTrj9n4kN9raiodbL9Bp4ZWc5wgPuMcyOI2as0VWL75oIDe+oPHzDy9xLU7UrNts1MPE2bt7jF7c3GS5YeoMKbkJBYSjw7p2sukDhwrjdGfsF968OSrLQ6jElxnGTN2clRvJkictL9wlvoMwi0Fg76www0eUcbvUMqVNaJ8F0zpcNR/N2nK8IzW+GnUBsX0,iv:DKljcZZR7lNFow6x3wn1nCJnx7Yz9F8ew2WaCsfGx+4=,tag:aN3Pl2GQ7BBlCNsu35iP0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:oX0w/qq2ow27H+seHf+MYEmj4bBHddH4IwhP/0VI7z/1osMcA35PjO2GA6DWr6Ct1rsZnZPHKYfBN0R2TltVOdesv5o6ACeNLkJMCn/ToX6adgWkMa9be3gSqaDpyjSCxA57Vm/qaC8coBi9MwgztHLXni4v+zRdU98s7Otq1D1qqJ8zVEtIFqqNsdnJ7W8coF3ekIVbSMRrvt/gbzghrpIYXua4BdyVoG2pPCyGEhMkUO+VVAwjkC2HWBxUAb0HLyi1fTpUY/HHiV1wDg==,iv:cjymvG2FRi569z4LxSokRIhLO+zVIMQb9CmX/jcmfpY=,tag:fjoUEu1Db8psKgXwHDJ65A==,type:str]
    known_hosts: ENC[AES256_GCM,data:VFQK+iT8lURf9n+GTBfqqi3KoQvthuyx4azK/fcjvk+2xfZPo6RjIKTI0FMTEluZg4gB/YQ3DmNbTt6M8KnXsEItOjCaRwFLpgBAi7mTXHePQpq43Q0k3I1QzwH9ihkS9bbp0YXpqWPSNmXYgk4yi+mcZdlaG7OMwTiaye0i91FC9SzammaaM3ELEckoR+iLcSKNzaexrqTw9Ei07RrQvb3yVKhMjBk6tB99,iv:l8ntt1EAGD3JOKYPCeSQqxiokdIywT4Davy3fvJWXUI=,tag:VTAsKIIHGNxZlBN5NZ2z9Q==,type:str]
sops:
    age:
        - recipient: age1mnqn4cexq7739pldt4mvq3cd6mu4h956cxha4f47r5v5aetd03nqlgp9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWmNNTXZleWxMRTNnb0RO
            UkNReTJlNFhiRWJTSFlwQ09ubkUzOTRsc1RFCkVlZEU1cld6WlN1ekxPNXh4M1M1
            WFBPaGdTK0NweW9zN0t5M2JzcXRiN2sKLS0tIE5tQnZLOHRkbXVuY2RJUWFmanli
            eWpUMmw0VjI5M2djKzBJOG9qOEhxazgKtNN6wG6xFrij2u3yBTmSo5zoy4JV0yy2
            WMYmPS23z0s/cey/H7Frr3eeKsJLPr9Q95Z8vqoEvD/g1NNWDTC/WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T05:03:53Z"
    mac: ENC[AES256_GCM,data:9T/49ZUqf4C3W7DNUlCdy3LiRBqTCwBwC3VA47JVxcJ/hK+hoCRBdCzeAIftKJVPvAFB9FaVySKoEB4pHOtweHKleQB/a0wXwq568qpake44wFoADGhAVVT6h5yidHQGdPbHQmY9KtbQQPlEI5rTQiJU5DktLNtTSIBhYNQAkHY=,iv:WQ42G1MEab68W8+NwgO+4Ov/lEJ5H9sm3fCWbnki1Jw=,tag:gHpan2ELsC7eWFavToM5jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
