apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: budget
  namespace: budget
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate:
        "{{range .Changed.Changes}}{{print .OldValue}} -> {{println
        .NewValue}}{{end}}"
    push:
      branch: main
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: primary
  update:
    path: ./cluster/budget
    strategy: Setters
