apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 87.17.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  values:
    prometheus:
      ingress:
        enabled: false
        ingressClassName: nginx
        hosts:
          - prometheus.local
        paths:
          - "/"
        pathType: Prefix
    grafana:
      ingress:
        enabled: false
        ingressClassName: nginx
        hosts:
          - grafana.local
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["alertname", "cluster", "service"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: "mail"
          routes:
            - receiver: "mail"
              matchers:
                - severity=warning
                - severity=critical
        receivers:
          - name: "mail"
            email_configs:
              - to: "kruvaishnav20@gmail.com"

    additionalPrometheusRulesMap:
      budget-app-alerts:
        groups:
          - name: BudgetAppAlerts
            rules:
            - alert: DeploymentSpecChanged
              expr: |
                changes(kube_deployment_status_observed_generation{namespace='budget'}[5m]) > 0
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: "Deployment {{ $labels.deployment }} has been updated"
                description: "The configuration for deployment '{{ $labels.deployment }}' in namespace '{{ $labels.namespace }}' has changed. This indicates a new rollout has likely started. Current generation: {{ $value }}."
            - alert: DeploymentDeleted
              expr: |
                absent(kube_deployment_created{namespace='budget'})
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: "Kubernetes Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has been deleted."
                description: "The 'kube_deployment_created' metric for deployment '{{ $labels.deployment }}' in namespace '{{ $labels.namespace }}' is no longer present. This indicates the Deployment has likely been deleted. Please verify."
